#ifndef VOXY_CONFIG_H
#define VOXY_CONFIG_H

#define CHUNK_WIDTH 16

#define ETHER_HEIGHT 128

#define GENERATOR_DISTANCE 8

#define RENDERER_LOAD_DISTANCE   4
#define RENDERER_UNLOAD_DISTANCE 64

#endif // VOXY_CONFIG_H
