#ifndef VOXY_CONFIG_H
#define VOXY_CONFIG_H

#define CAVE_WORM_RATIO 1e-2

#define CAVE_WORM_TRIAL 10
#define CAVE_WORM_NODE_COUNT 100
#define CAVE_WORM_NODE_RADIUS 3.0f
#define CAVE_WORM_STEP 1.0f

#define CHUNK_WIDTH 16

#define GENERATOR_DISTANCE 4

#define RENDERER_LOAD_DISTANCE   4
#define RENDERER_UNLOAD_DISTANCE 64

#endif // VOXY_CONFIG_H
