#ifndef VOXY_SCENE_MAIN_GAME_CONFIG_H
#define VOXY_SCENE_MAIN_GAME_CONFIG_H

#define CHUNK_WIDTH 16

#define WINDOW_WIDTH  1024
#define WINDOW_HEIGHT 720
#define WINDOW_TITLE "voxy"

#define MOD_FILEPATH "mod/mod.so"

#define WORLD_DIRPATH "world"

#define RENDERER_LOAD_DISTANCE   4
#define RENDERER_UNLOAD_DISTANCE 64

#define PHYSICS_GRAVITY 9.8f
#define PHYSICS_DRAG_GROUND 2.0f
#define PHYSICS_DRAG_AIR    0.5f

#endif // VOXY_SCENE_MAIN_GAME_CONFIG_H
